### PR TITLE
Triggering rebuild.

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
@ocefpaf seeking help! 

I think I messed something up. I asked for the conda-forge admin to make it noarch Python and then realized I couldn't do that because I use some Py36-only features in the codebase. I then reverted just one change (`skip: True [py<36]`), and it now looks like the package isn't building onto conda-forge. Is there a mistake I made somewhere?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender. If you make a change like that, you need to rerender again.

**Comment by ocefpaf** [comment]
@ericmjl the re-rendering that @isuruf issued fixed that but now it seems that `seaborn` is missing. I just added that.

**Comment by ericmjl** [comment]
@isuruf @ocefpaf thanks for the help! Seems like re-rendering is a generally safe thing to do as a default debugging tool, unless it's some other obvious problem (e.g. CircleCI's authentication thingy).

**Comment by ocefpaf** [comment]
> Seems like re-rendering is a generally safe thing to do as a default debugging tool,

Yep. That way you will update the feedstock boilerplate with the latest fixes. However, in that case, it was a necessary step due to the change in the `skip` section.

https://conda-forge.org/docs/conda_smithy.html#when-should-we-re-render

**Pull request merged**
