### PR TITLE
updated recipe for 0.3.2 release

### PR DESCRIPTION
**Pull request by ericmjl**
Also re-rendered with conda-smithy.

### CODE REVIEW

**Comment by ericmjl** [comment]
@ocefpaf hello from Boston again! :smile: Hope things are well for you. I'm just wondering what's up with Travis - is it just a lot of jobs going on? nxviz has been queued for over 10 hours now.

**Comment by ocefpaf** [comment]
I don't see any issue since Sep 14th on https://www.traviscistatus.com
I guess that Travis-CI OS X images are in high demand.

This feedstock is a good candidate for `noarch` and that would build quite fast using only CircleCI.
See https://conda-forge.org/docs/meta.html#building-noarch-packages for more details.

However, conda would allow it to be installed on `Python <3.5` breaking the skip statement with you have there. @jjhelmus I am correct assuming that? If so, is there a work around we can do here?

**Comment by ocefpaf** [comment]
PS: there is a slim change that Travis-CI will fail when everything else passed. You can go ahead and merge this to cash the Linux and Windows packages IMO.

**Comment by ericmjl** [comment]
@ocefpaf thanks for the reply! :smile: I'm happy to wait it out then; upon thinking more about it, there's nothing particularly time-sensitive about this package.

**Comment by ericmjl** [comment]
That said, if I can make it py36 and higher while using noarch (somehow) I'd be more than happy to learn how to make it happen!

**Comment by ocefpaf** [comment]
OK. BTW, as soon as we get an answer for [this](https://gitter.im/conda-forge/conda-forge.github.io?at=59c10425bac826f054d7544f) question we'll know if we can make this feedstock `noarch`.

**Pull request merged**
