### PR TITLE
version bump 0.3.0

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
ping @jakirkham @ocefpaf @msarahan just wondering if my `meta.yaml` is written incorrectly? `nxviz` depends on `polcart`, which I included in the `run` section of `requirements`, but not in the `build` section. Or do I have it backwards?

**Comment by ocefpaf** [comment]
@ericmjl because `nxviz` imports itself in `setup.py` all the `run` dependencies are needed at build time. See https://github.com/ericmjl/nxviz/blob/master/setup.py#L1 

PS: that is usually frowned upon when building your `setup.py`. There are some patterns to extract the version and etc from the `__init__.py` without importing the module.

**Comment by ericmjl** [comment]
@ocefpaf again, you save my day. Thanks a lot! :smile:

**Comment by ocefpaf** [comment]
> @ocefpaf again, you save my day. Thanks a lot! :smile:

No problem. (Although my lazy self would just repeat the `run` dependencies in the `build` section :wink:
But that is better.

**Pull request merged**
