### PR TITLE
nxviz 0.3.5

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
@ocefpaf sorry to bother you here... but I was just wondering how do I fix the AppVeyor issues? I've tried looking around for the error `The batch file cannot be done` on conda-forge, but can't seem to find anything.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

@ericmjl rerendering should fix it.

**Comment by ericmjl** [comment]
Ok! Good to know we can "please rerender" here, I've been stuck with rerendering locally. Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
> Ok! Good to know we can "please rerender" here

We are very lazy on conda-forge :smile: 
[Here](https://conda-forge.org/docs/webservice.html) is everything the bot can do for you.

PS: we should start tweeting issues that are fixed when re-rendering, like the "batch not found," so people are not lost when they happen.

**Pull request merged**
